<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.4.1" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.4.1" />
    <PackageVersion Include="NSec.Cryptography" Version="26.4.0" />
    <PackageVersion Include="SQLite3MC.PCLRaw.bundle" Version="2.4.0" />
    <PackageVersion Include="System.Security.Cryptography.ProtectedData" Version="10.0.12" />
  </ItemGroup>
</Project>
